---
title: "Nucleoside_transporter"
author: "Alisa Schmidt"
date: "10.05.2024"
output:
  html_document:
    df_print: paged
---
```{r include=FALSE}
library(DESeq2)
library(ggplot2)
library(tidyr)
library(tidyverse)
```

**Check for nucleoside transporters**
**load the DeSeq data**

```{r}
load("/Users/alisc/Desktop/CRG/DeSeq R/DDS_file.RData")
count_data <- counts(dds)
rld <- rlog(dds, blind = TRUE) #normalize the counts first
rld_counts <- assay(rld)
```
Check ensemble ID for
SLC29A1: ENSG00000112759
SLC29A2: ENSG00000174669

```{r}
gene_symbols <- c("ENSG00000112759", "ENSG00000174669")
filtered_counts <- rld_counts[rownames(count_data) %in% gene_symbols, ]

```

```{r}
filtered_counts_2<- t(filtered_counts)
filtered_counts_2 <- as.data.frame(filtered_counts_2)
filtered_counts_2$condition <- rownames(filtered_counts_2)
filtered_counts_2 <- filtered_counts_2 %>%
  mutate(condition = sub("[0-9]+$", "", condition))
filtered_counts_2 <- filtered_counts_2[!filtered_counts_2$condition %in% c("K0NES"),]

SLC29A1 <- filtered_counts_2[,c(1,3)]
SLC29A2 <- filtered_counts_2[,c(2,3)]
```

*Plot counts per condition*
```{r}
pdf("/Users/alisc/Desktop/CRG/final_figures/nucleotide_transporter/gene_count.pdf")
ggplot(SLC29A1, aes(condition, ENSG00000112759, fill=condition )) + geom_bar(stat="identity", width = 0.5) + 
  labs(x = "", y = "normalised gene count", title = "SLC29A1") + theme_classic() +  scale_fill_grey() +theme(legend.position = "none")
ggplot(SLC29A2, aes(condition, ENSG00000174669, fill=condition )) + geom_bar(stat="identity", width = 0.5) + 
  labs(x = "", y = "normalised gene count", title = "SLC29A2") + theme_classic() +  scale_fill_grey() +theme(legend.position = "none")
dev.off()
```
